CREATE TABLE tb_projects
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title           VARCHAR(255)                            NOT NULL,
    description     TEXT,
    category        VARCHAR(255),
    client_name     VARCHAR(255),
    completion_date date,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tb_projects PRIMARY KEY (id)
);

DROP SEQUENCE tb_projects_id_seq CASCADE;